In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

from IPython.display import display

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
PROJECT_DIR = Path("../")
RESULTS_DIR = PROJECT_DIR / "results"
DATA_DIR = PROJECT_DIR / "data"

print("Project:", PROJECT_DIR.resolve())
print("Results:", RESULTS_DIR.resolve())
print("Data:", DATA_DIR.resolve())

Project: C:\Users\ASUS\Documents\Smart-Tourism-Recommendation
Results: C:\Users\ASUS\Documents\Smart-Tourism-Recommendation\results
Data: C:\Users\ASUS\Documents\Smart-Tourism-Recommendation\data

In [3]:
evaluation_files = list(DATA_DIR.rglob("evaluation_cases_clean.csv"))

print("Evaluation files found:", len(evaluation_files))

for file in evaluation_files:
    print(file)

Evaluation files found: 1
..\data\processed\evaluation_cases_clean.csv

In [4]:
evaluation_path = evaluation_files[0]

evaluation_cases = pd.read_csv(evaluation_path)

print("Evaluation cases loaded successfully.")
print("Shape:", evaluation_cases.shape)

print("\nColumns:")
print(evaluation_cases.columns.tolist())

Evaluation cases loaded successfully.
Shape: (500, 27)

Columns:
['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'travel_style', 'starting_location', 'preferred_interests', 'preferred_crowd', 'preferred_weather', 'destination_name', 'destination_category', 'estimated_cost_lkr', 'duration_hours', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5', 'data_status']

In [5]:
display(evaluation_cases.head(10))

,case_id,user_id,destination_id,scenario_id,user_budget_lkr_per_day,trip_duration_days,travel_style,starting_location,preferred_interests,preferred_crowd,...,budget_score,sustainability_score,crowd_fit_score,context_score,distance_score,sentiment_score,popularity_score,overall_hybrid_score,relevance_rating_1_to_5,data_status
0,C001,U001,D001,1,5000,1,budget,colombo,nature;photography,low,...,0.0,0.57,0.84,0.516,0.621,0.716,0.41,0.505,3,derived_from_synthetic_profile_and_research_se...
1,C002,U001,D012,2,5000,1,budget,colombo,nature;photography,low,...,0.8,0.58,0.82,0.866,0.201,0.814,0.43,0.627,4,derived_from_synthetic_profile_and_research_se...
2,C003,U001,D023,3,5000,1,budget,colombo,nature;photography,low,...,0.6,0.63,0.95,0.461,0.738,0.814,0.30,0.781,4,derived_from_synthetic_profile_and_research_se...
3,C004,U001,D034,4,5000,1,budget,colombo,nature;photography,low,...,0.8,0.67,0.88,0.520,0.679,0.825,0.37,0.811,4,derived_from_synthetic_profile_and_research_se...
4,C005,U001,D045,5,5000,1,budget,colombo,nature;photography,low,...,0.6,0.57,0.83,0.520,0.405,0.751,0.42,0.576,3,derived_from_synthetic_profile_and_research_se...
5,C006,U001,D001,6,5000,1,budget,colombo,nature;photography,low,...,0.0,0.57,0.84,0.413,0.621,0.716,0.41,0.495,3,derived_from_synthetic_profile_and_research_se...
6,C007,U001,D012,7,5000,1,budget,colombo,nature;photography,low,...,0.8,0.58,0.82,0.693,0.201,0.814,0.43,0.610,3,derived_from_synthetic_profile_and_research_se...
7,C008,U001,D023,8,5000,1,budget,colombo,nature;photography,low,...,0.6,0.63,0.95,0.369,0.738,0.814,0.30,0.772,4,derived_from_synthetic_profile_and_research_se...
8,C009,U001,D034,9,5000,1,budget,colombo,nature;photography,low,...,0.8,0.67,0.88,0.416,0.679,0.825,0.37,0.800,4,derived_from_synthetic_profile_and_research_se...
9,C010,U001,D045,10,5000,1,budget,colombo,nature;photography,low,...,0.6,0.57,0.83,0.416,0.405,0.751,0.42,0.566,3,derived_from_synthetic_profile_and_research_se...

In [6]:
print("Rows:", len(evaluation_cases))
print("Users:", evaluation_cases["user_id"].nunique())

Rows: 500
Users: 50

In [7]:
recommendation_path = (
    RESULTS_DIR / "demand_aware_recommendations.csv"
)

final_recommendations = pd.read_csv(
    recommendation_path
)

print("Demand-aware recommendations loaded.")
print("Shape:", final_recommendations.shape)

print("\nColumns:")
print(final_recommendations.columns.tolist())

Demand-aware recommendations loaded.
Shape: (500, 17)

Columns:
['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'predicted_crowd_score', 'predicted_crowd_level', 'seasonality_score', 'sbert_hybrid_score', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'demand_explanation']

In [8]:
print("Users:",
      final_recommendations["user_id"].nunique())

print("Rows:",
      len(final_recommendations))

print(
    "Rank range:",
    final_recommendations["demand_aware_rank"].min(),
    "to",
    final_recommendations["demand_aware_rank"].max()
)

print(
    "\nRows per user:"
)

display(
    final_recommendations
    .groupby("user_id")
    .size()
    .value_counts()
)

Users: 50
Rows: 500
Rank range: 1 to 10

Rows per user:

10    50
Name: count, dtype: int64

In [9]:
b5_path = (
    RESULTS_DIR /
    "b5_sbert_semantic_recommendations.csv"
)

b5_recommendations = pd.read_csv(b5_path)

print("B5 recommendations loaded.")
print("Shape:", b5_recommendations.shape)

print("\nColumns:")
print(b5_recommendations.columns.tolist())

B5 recommendations loaded.
Shape: (500, 20)

Columns:
['user_id', 'destination_id', 'content_similarity', 'content_similarity_normalized', 'sbert_similarity', 'sbert_similarity_normalized', 'interest_match', 'budget_fit', 'sustainability_fit', 'context_score', 'sbert_hybrid_score', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'seasonality_score', 'rank']

In [10]:
print(
    "B5 users:",
    b5_recommendations["user_id"].nunique()
)

print(
    "B5 rows:",
    len(b5_recommendations)
)

print(
    "B5 rank range:",
    b5_recommendations["rank"].min(),
    "to",
    b5_recommendations["rank"].max()
)

B5 users: 50
B5 rows: 500
B5 rank range: 1 to 10

In [11]:
print("Evaluation columns:")
for i, col in enumerate(evaluation_cases.columns):
    print(i, ":", col)

Evaluation columns:
0 : case_id
1 : user_id
2 : destination_id
3 : scenario_id
4 : user_budget_lkr_per_day
5 : trip_duration_days
6 : travel_style
7 : starting_location
8 : preferred_interests
9 : preferred_crowd
10 : preferred_weather
11 : destination_name
12 : destination_category
13 : estimated_cost_lkr
14 : duration_hours
15 : distance_km
16 : preference_score
17 : budget_score
18 : sustainability_score
19 : crowd_fit_score
20 : context_score
21 : distance_score
22 : sentiment_score
23 : popularity_score
24 : overall_hybrid_score
25 : relevance_rating_1_to_5
26 : data_status

In [12]:
display(
    evaluation_cases.head(20)
)

,case_id,user_id,destination_id,scenario_id,user_budget_lkr_per_day,trip_duration_days,travel_style,starting_location,preferred_interests,preferred_crowd,...,budget_score,sustainability_score,crowd_fit_score,context_score,distance_score,sentiment_score,popularity_score,overall_hybrid_score,relevance_rating_1_to_5,data_status
0,C001,U001,D001,1,5000,1,budget,colombo,nature;photography,low,...,0.000,0.57,0.84,0.516,0.621,0.716,0.41,0.505,3,derived_from_synthetic_profile_and_research_se...
1,C002,U001,D012,2,5000,1,budget,colombo,nature;photography,low,...,0.800,0.58,0.82,0.866,0.201,0.814,0.43,0.627,4,derived_from_synthetic_profile_and_research_se...
2,C003,U001,D023,3,5000,1,budget,colombo,nature;photography,low,...,0.600,0.63,0.95,0.461,0.738,0.814,0.30,0.781,4,derived_from_synthetic_profile_and_research_se...
3,C004,U001,D034,4,5000,1,budget,colombo,nature;photography,low,...,0.800,0.67,0.88,0.520,0.679,0.825,0.37,0.811,4,derived_from_synthetic_profile_and_research_se...
4,C005,U001,D045,5,5000,1,budget,colombo,nature;photography,low,...,0.600,0.57,0.83,0.520,0.405,0.751,0.42,0.576,3,derived_from_synthetic_profile_and_research_se...
5,C006,U001,D001,6,5000,1,budget,colombo,nature;photography,low,...,0.000,0.57,0.84,0.413,0.621,0.716,0.41,0.495,3,derived_from_synthetic_profile_and_research_se...
6,C007,U001,D012,7,5000,1,budget,colombo,nature;photography,low,...,0.800,0.58,0.82,0.693,0.201,0.814,0.43,0.610,3,derived_from_synthetic_profile_and_research_se...
7,C008,U001,D023,8,5000,1,budget,colombo,nature;photography,low,...,0.600,0.63,0.95,0.369,0.738,0.814,0.30,0.772,4,derived_from_synthetic_profile_and_research_se...
8,C009,U001,D034,9,5000,1,budget,colombo,nature;photography,low,...,0.800,0.67,0.88,0.416,0.679,0.825,0.37,0.800,4,derived_from_synthetic_profile_and_research_se...
9,C010,U001,D045,10,5000,1,budget,colombo,nature;photography,low,...,0.600,0.57,0.83,0.416,0.405,0.751,0.42,0.566,3,derived_from_synthetic_profile_and_research_se...
10,C011,U002,D008,1,8000,2,moderate,kandy,beach;relaxation,medium,...,0.375,0.61,0.82,0.933,0.703,0.624,0.37,0.456,3,derived_from_synthetic_profile_and_research_se...
11,C012,U002,D019,2,8000,2,moderate,kandy,beach;relaxation,medium,...,0.625,0.62,0.77,0.924,0.985,0.710,0.32,0.526,3,derived_from_synthetic_profile_and_research_se...
12,C013,U002,D030,3,8000,2,moderate,kandy,beach;relaxation,medium,...,0.375,0.63,0.84,0.912,0.835,0.815,0.39,0.491,3,derived_from_synthetic_profile_and_research_se...
13,C014,U002,D041,4,8000,2,moderate,kandy,beach;relaxation,medium,...,0.875,0.58,0.80,0.913,0.691,0.738,0.35,0.832,4,derived_from_synthetic_profile_and_research_se...
14,C015,U002,D052,5,8000,2,moderate,kandy,beach;relaxation,medium,...,0.250,0.60,0.83,0.910,0.763,0.612,0.38,0.589,3,derived_from_synthetic_profile_and_research_se...
15,C016,U002,D008,6,8000,2,moderate,kandy,beach;relaxation,medium,...,0.375,0.61,0.82,0.746,0.703,0.624,0.37,0.437,3,derived_from_synthetic_profile_and_research_se...
16,C017,U002,D019,7,8000,2,moderate,kandy,beach;relaxation,medium,...,0.625,0.62,0.77,0.740,0.985,0.710,0.32,0.507,3,derived_from_synthetic_profile_and_research_se...
17,C018,U002,D030,8,8000,2,moderate,kandy,beach;relaxation,medium,...,0.375,0.63,0.84,0.729,0.835,0.815,0.39,0.473,3,derived_from_synthetic_profile_and_research_se...
18,C019,U002,D041,9,8000,2,moderate,kandy,beach;relaxation,medium,...,0.875,0.58,0.80,0.730,0.691,0.738,0.35,0.814,4,derived_from_synthetic_profile_and_research_se...
19,C020,U002,D052,10,8000,2,moderate,kandy,beach;relaxation,medium,...,0.250,0.60,0.83,0.728,0.763,0.612,0.38,0.571,3,derived_from_synthetic_profile_and_research_se...

In [13]:
for col in evaluation_cases.columns:
    print(
        "\nCOLUMN:",
        col,
        "\nTYPE:",
        evaluation_cases[col].dtype,
        "\nUNIQUE:",
        evaluation_cases[col].nunique()
    )

COLUMN: case_id
TYPE: str
UNIQUE: 500

COLUMN: user_id
TYPE: str
UNIQUE: 50

COLUMN: destination_id
TYPE: str
UNIQUE: 100

COLUMN: scenario_id
TYPE: int64
UNIQUE: 10

COLUMN: user_budget_lkr_per_day
TYPE: int64
UNIQUE: 6

COLUMN: trip_duration_days
TYPE: int64
UNIQUE: 5

COLUMN: travel_style
TYPE: str
UNIQUE: 3

COLUMN: starting_location
TYPE: str
UNIQUE: 10

COLUMN: preferred_interests
TYPE: str
UNIQUE: 10

COLUMN: preferred_crowd
TYPE: str
UNIQUE: 3

COLUMN: preferred_weather
TYPE: str
UNIQUE: 5

COLUMN: destination_name
TYPE: int64
UNIQUE: 100

COLUMN: destination_category
TYPE: str
UNIQUE: 32

COLUMN: estimated_cost_lkr
TYPE: int64
UNIQUE: 14

COLUMN: duration_hours
TYPE: float64
UNIQUE: 8

COLUMN: distance_km
TYPE: float64
UNIQUE: 244

COLUMN: preference_score
TYPE: float64
UNIQUE: 3

COLUMN: budget_score
TYPE: float64
UNIQUE: 47

COLUMN: sustainability_score
TYPE: float64
UNIQUE: 22

COLUMN: crowd_fit_score
TYPE: float64
UNIQUE: 52

COLUMN: context_score
TYPE: float64
UNIQUE: 237

COLUMN: distance_score
TYPE: float64
UNIQUE: 199

COLUMN: sentiment_score
TYPE: float64
UNIQUE: 79

COLUMN: popularity_score
TYPE: float64
UNIQUE: 24

COLUMN: overall_hybrid_score
TYPE: float64
UNIQUE: 296

COLUMN: relevance_rating_1_to_5
TYPE: int64
UNIQUE: 3

COLUMN: data_status
TYPE: str
UNIQUE: 1

In [14]:
evaluation = evaluation_cases.copy()

evaluation["user_id"] = evaluation["user_id"].astype(str)
evaluation["destination_id"] = evaluation["destination_id"].astype(str)

evaluation["relevance_rating_1_to_5"] = pd.to_numeric(
    evaluation["relevance_rating_1_to_5"],
    errors="coerce"
)

evaluation = evaluation.dropna(
    subset=["user_id", "destination_id", "relevance_rating_1_to_5"]
)

print("Evaluation data prepared.")
print("Rows:", len(evaluation))
print("Users:", evaluation["user_id"].nunique())
print("Destinations:", evaluation["destination_id"].nunique())

print("\nRelevance rating distribution:")
print(
    evaluation["relevance_rating_1_to_5"]
    .value_counts()
    .sort_index()
)

Evaluation data prepared.
Rows: 500
Users: 50
Destinations: 100

Relevance rating distribution:
relevance_rating_1_to_5
2     20
3    359
4    121
Name: count, dtype: int64

In [15]:
evaluation["relevant"] = (
    evaluation["relevance_rating_1_to_5"] >= 4
).astype(int)

print("Relevant cases:",
      evaluation["relevant"].sum())

print("Non-relevant cases:",
      (evaluation["relevant"] == 0).sum())

print(
    "\nRelevant percentage:",
    round(
        evaluation["relevant"].mean() * 100,
        2
    ),
    "%"
)

Relevant cases: 121
Non-relevant cases: 379

Relevant percentage: 24.2 %

In [16]:
evaluation["relevant"] = (
    evaluation["relevance_rating_1_to_5"] >= 4
).astype(int)

print("Relevant cases:",
      evaluation["relevant"].sum())

print("Non-relevant cases:",
      (evaluation["relevant"] == 0).sum())

print(
    "\nRelevant percentage:",
    round(
        evaluation["relevant"].mean() * 100,
        2
    ),
    "%"
)

Relevant cases: 121
Non-relevant cases: 379

Relevant percentage: 24.2 %

In [17]:
predicted = final_recommendations[
    [
        "user_id",
        "destination_id",
        "demand_aware_rank",
        "demand_aware_score"
    ]
].copy()

predicted["user_id"] = predicted["user_id"].astype(str)
predicted["destination_id"] = predicted["destination_id"].astype(str)

print("Predicted recommendations prepared.")
print("Rows:", len(predicted))
print("Users:", predicted["user_id"].nunique())

Predicted recommendations prepared.
Rows: 500
Users: 50

In [18]:
evaluation_table = predicted.merge(
    evaluation[
        [
            "user_id",
            "destination_id",
            "relevance_rating_1_to_5",
            "relevant"
        ]
    ],
    on=["user_id", "destination_id"],
    how="left"
)

print("Evaluation table created.")
print("Shape:", evaluation_table.shape)

display(evaluation_table.head(20))

Evaluation table created.
Shape: (528, 6)

,user_id,destination_id,demand_aware_rank,demand_aware_score,relevance_rating_1_to_5,relevant
0,U001,D048,1,0.638371,NaN,NaN
1,U001,D051,2,0.614931,NaN,NaN
2,U001,D029,3,0.588797,NaN,NaN
3,U001,D054,4,0.558387,NaN,NaN
4,U001,D053,5,0.547760,NaN,NaN
5,U001,D020,6,0.524035,NaN,NaN
6,U001,D066,7,0.516999,NaN,NaN
7,U001,D098,8,0.489361,NaN,NaN
8,U001,D070,9,0.459681,NaN,NaN
9,U001,D052,10,0.439264,NaN,NaN
10,U002,D015,1,0.704641,NaN,NaN
11,U002,D043,2,0.656512,NaN,NaN
12,U002,D054,3,0.640943,NaN,NaN
13,U002,D041,4,0.616324,4.0,1.0
14,U002,D041,4,0.616324,4.0,1.0
15,U002,D055,5,0.602363,NaN,NaN
16,U002,D047,6,0.597585,NaN,NaN
17,U002,D040,7,0.597414,NaN,NaN
18,U002,D079,8,0.574862,NaN,NaN
19,U002,D088,9,0.574461,NaN,NaN

In [19]:
print(
    "Missing relevance ratings:",
    evaluation_table[
        "relevance_rating_1_to_5"
    ].isna().sum()
)

print(
    "Matched recommendations:",
    evaluation_table[
        "relevance_rating_1_to_5"
    ].notna().sum()
)

Missing relevance ratings: 472
Matched recommendations: 56

In [21]:
coverage = (
    evaluation_table
    .groupby("user_id")
    .agg(
        recommendations=("destination_id", "count"),
        matched_cases=("relevance_rating_1_to_5", "count")
    )
    .reset_index()
)

coverage["coverage_percentage"] = (
    coverage["matched_cases"]
    / coverage["recommendations"]
    * 100
)

display(coverage)

print("Total users:", len(coverage))
print(
    "Users with at least one matched case:",
    (coverage["matched_cases"] > 0).sum()
)

print(
    "Users with zero matched cases:",
    (coverage["matched_cases"] == 0).sum()
)

   user_id  recommendations  matched_cases  coverage_percentage
0     U001               10              0             0.000000
1     U002               11              2            18.181818
2     U003               11              2            18.181818
3     U004               12              4            33.333333
4     U005               11              2            18.181818
5     U006               10              0             0.000000
6     U007               10              0             0.000000
7     U008               10              0             0.000000
8     U009               10              0             0.000000
9     U010               12              4            33.333333
10    U011               10              0             0.000000
11    U012               10              0             0.000000
12    U013               11              2            18.181818
13    U014               11              2            18.181818
14    U015               10              0             0.000000
15    U016               10              0             0.000000
16    U017               10              0             0.000000
17    U018               10              0             0.000000
18    U019               10              0             0.000000
19    U020               10              0             0.000000
20    U021               12              4            33.333333
21    U022               10              0             0.000000
22    U023               10              0             0.000000
23    U024               12              4            33.333333
24    U025               12              4            33.333333
25    U026               11              2            18.181818
26    U027               10              0             0.000000
27    U028               11              2            18.181818
28    U029               10              0             0.000000
29    U030               11              2            18.181818
30    U031               10              0             0.000000
31    U032               10              0             0.000000
32    U033               10              0             0.000000
33    U034               10              0             0.000000
34    U035               10              0             0.000000
35    U036               11              2            18.181818
36    U037               10              0             0.000000
37    U038               11              2            18.181818
38    U039               10              0             0.000000
39    U040               12              4            33.333333
40    U041               10              0             0.000000
41    U042               11              2            18.181818
42    U043               11              2            18.181818
43    U044               10              0             0.000000
44    U045               10              0             0.000000
45    U046               11              2            18.181818
46    U047               11              2            18.181818
47    U048               11              2            18.181818
48    U049               11              2            18.181818
49    U050               10              0             0.000000

Total users: 50
Users with at least one matched case: 22
Users with zero matched cases: 28

In [22]:
evaluation_summary = (
    evaluation
    .groupby("user_id")
    .agg(
        evaluation_cases=("destination_id", "count"),
        relevant_destinations=("relevant", "sum")
    )
    .reset_index()
)

display(evaluation_summary)

print(
    "Evaluation cases per user:"
)

print(
    evaluation_summary[
        "evaluation_cases"
    ].value_counts()
)

   user_id  evaluation_cases  relevant_destinations
0     U001                10                      5
1     U002                10                      2
2     U003                10                      4
3     U004                10                      3
4     U005                10                      4
5     U006                10                      0
6     U007                10                      2
7     U008                10                      1
8     U009                10                      2
9     U010                10                      4
10    U011                10                      6
11    U012                10                      0
12    U013                10                      2
13    U014                10                      3
14    U015                10                      0
15    U016                10                      0
16    U017                10                      4
17    U018                10                      0
18    U019                10                      0
19    U020                10                      4
20    U021                10                      4
21    U022                10                      2
22    U023                10                      0
23    U024                10                      4
24    U025                10                      4
25    U026                10                      2
26    U027                10                      4
27    U028                10                      1
28    U029                10                      0
29    U030                10                      2
30    U031                10                      2
31    U032                10                      2
32    U033                10                      0
33    U034                10                      4
34    U035                10                      0
35    U036                10                      0
36    U037                10                      2
37    U038                10                      6
38    U039                10                      4
39    U040                10                      4
40    U041                10                      4
41    U042                10                      2
42    U043                10                      4
43    U044                10                      6
44    U045                10                      0
45    U046                10                      0
46    U047                10                      6
47    U048                10                      0
48    U049                10                      4
49    U050                10                      2

Evaluation cases per user:
evaluation_cases
10    50
Name: count, dtype: int64

In [23]:
ground_truth = (
    evaluation[
        [
            "user_id",
            "destination_id",
            "relevance_rating_1_to_5",
            "relevant"
        ]
    ]
    .copy()
)

print("Ground truth created.")
print("Rows:", len(ground_truth))
print("Users:", ground_truth["user_id"].nunique())

display(ground_truth.head(10))

Ground truth created.
Rows: 500
Users: 50

  user_id destination_id  relevance_rating_1_to_5  relevant
0    U001           D001                        3         0
1    U001           D012                        4         1
2    U001           D023                        4         1
3    U001           D034                        4         1
4    U001           D045                        3         0
5    U001           D001                        3         0
6    U001           D012                        3         0
7    U001           D023                        4         1
8    U001           D034                        4         1
9    U001           D045                        3         0

In [24]:
relevant_ground_truth = ground_truth[
    ground_truth["relevant"] == 1
].copy()

print(
    "Relevant evaluation cases:",
    len(relevant_ground_truth)
)

print(
    "Users with at least one relevant destination:",
    relevant_ground_truth["user_id"].nunique()
)

display(
    relevant_ground_truth.head(20)
)

Relevant evaluation cases: 121
Users with at least one relevant destination: 36

   user_id destination_id  relevance_rating_1_to_5  relevant
1     U001           D012                        4         1
2     U001           D023                        4         1
3     U001           D034                        4         1
7     U001           D023                        4         1
8     U001           D034                        4         1
13    U002           D041                        4         1
18    U002           D041                        4         1
22    U003           D037                        4         1
23    U003           D048                        4         1
27    U003           D037                        4         1
28    U003           D048                        4         1
30    U004           D022                        4         1
32    U004           D044                        4         1
35    U004           D022                        4         1
40    U005           D029                        4         1
43    U005           D062                        4         1
45    U005           D029                        4         1
48    U005           D062                        4         1
63    U007           D076                        4         1
68    U007           D076                        4         1

In [25]:
def calculate_hit_based_metrics(
    recommendations,
    ground_truth,
    rank_column,
    k_values=[1, 3, 5, 10]
):
    
    results = []
    
    # Relevant destinations for each user
    relevant_by_user = (
        ground_truth[
            ground_truth["relevant"] == 1
        ]
        .groupby("user_id")["destination_id"]
        .apply(set)
        .to_dict()
    )
    
    for k in k_values:
        
        precisions = []
        recalls = []
        hits = []
        
        for user_id, group in recommendations.groupby(
            "user_id"
        ):
            
            top_k = group[
                group[rank_column] <= k
            ].sort_values(rank_column)
            
            recommended_ids = set(
                top_k["destination_id"]
            )
            
            relevant_ids = relevant_by_user.get(
                user_id,
                set()
            )
            
            intersection = (
                recommended_ids
                & relevant_ids
            )
            
            hit_count = len(intersection)
            
            # Precision@K
            precision = (
                hit_count / k
                if k > 0
                else 0
            )
            
            # Recall@K
            if len(relevant_ids) > 0:
                recall = (
                    hit_count
                    / len(relevant_ids)
                )
            else:
                recall = np.nan
            
            precisions.append(precision)
            recalls.append(recall)
            hits.append(hit_count)
        
        results.append({
            "k": k,
            "precision": np.mean(precisions),
            "recall": np.nanmean(recalls),
            "average_hits": np.mean(hits)
        })
    
    return pd.DataFrame(results)

In [26]:
demand_aware_metrics = calculate_hit_based_metrics(
    final_recommendations,
    ground_truth,
    "demand_aware_rank"
)

print("Demand-aware evaluation:")
display(demand_aware_metrics)

Demand-aware evaluation:

    k  precision    recall  average_hits
0   1      0.060  0.055556          0.06
1   3      0.060  0.138889          0.18
2   5      0.056  0.217593          0.28
3  10      0.042  0.337963          0.42

In [27]:
b5_eval_clean = b5_recommendations[
    [
        "user_id",
        "destination_id",
        "rank"
    ]
].copy()

b5_eval_clean["user_id"] = (
    b5_eval_clean["user_id"].astype(str)
)

b5_eval_clean["destination_id"] = (
    b5_eval_clean["destination_id"].astype(str)
)

print(
    "B5 rows:",
    len(b5_eval_clean)
)

print(
    "B5 users:",
    b5_eval_clean["user_id"].nunique()
)

B5 rows: 500
B5 users: 50

In [28]:
b5_metrics = calculate_hit_based_metrics(
    b5_eval_clean,
    ground_truth,
    "rank"
)

print("B5 evaluation:")
display(b5_metrics)

B5 evaluation:

    k  precision    recall  average_hits
0   1      0.080  0.069444          0.08
1   3      0.060  0.162037          0.18
2   5      0.044  0.189815          0.22
3  10      0.042  0.337963          0.42

In [29]:
comparison_metrics = demand_aware_metrics.merge(
    b5_metrics,
    on="k",
    suffixes=(
        "_demand_aware",
        "_b5"
    )
)

display(comparison_metrics)

,k,precision_demand_aware,recall_demand_aware,average_hits_demand_aware,precision_b5,recall_b5,average_hits_b5
0,1,0.060,0.055556,0.06,0.080,0.069444,0.08
1,3,0.060,0.138889,0.18,0.060,0.162037,0.18
2,5,0.056,0.217593,0.28,0.044,0.189815,0.22
3,10,0.042,0.337963,0.42,0.042,0.337963,0.42

In [30]:
comparison_metrics["precision_change"] = (
    comparison_metrics["precision_demand_aware"]
    - comparison_metrics["precision_b5"]
)

comparison_metrics["recall_change"] = (
    comparison_metrics["recall_demand_aware"]
    - comparison_metrics["recall_b5"]
)

comparison_metrics["hit_change"] = (
    comparison_metrics["average_hits_demand_aware"]
    - comparison_metrics["average_hits_b5"]
)

display(comparison_metrics)

,k,precision_demand_aware,recall_demand_aware,average_hits_demand_aware,precision_b5,recall_b5,average_hits_b5,precision_change,recall_change,hit_change
0,1,0.060,0.055556,0.06,0.080,0.069444,0.08,-0.020,-0.013889,-0.02
1,3,0.060,0.138889,0.18,0.060,0.162037,0.18,0.000,-0.023148,0.00
2,5,0.056,0.217593,0.28,0.044,0.189815,0.22,0.012,0.027778,0.06
3,10,0.042,0.337963,0.42,0.042,0.337963,0.42,0.000,0.000000,0.00

In [31]:
def calculate_ndcg_from_ground_truth(
    recommendations,
    ground_truth,
    rank_column,
    k
):
    
    merged = recommendations.merge(
        ground_truth[
            [
                "user_id",
                "destination_id",
                "relevance_rating_1_to_5"
            ]
        ],
        on=[
            "user_id",
            "destination_id"
        ],
        how="left"
    )
    
    merged["relevance_rating_1_to_5"] = (
        merged["relevance_rating_1_to_5"]
        .fillna(0)
    )
    
    scores = []
    
    for user_id, group in merged.groupby(
        "user_id"
    ):
        
        group = group.sort_values(
            rank_column
        )
        
        top_k = group.head(k)
        
        relevance = (
            top_k[
                "relevance_rating_1_to_5"
            ]
            .values
        )
        
        if len(relevance) == 0:
            continue
        
        dcg = 0.0
        
        for i, rel in enumerate(
            relevance,
            start=1
        ):
            dcg += (
                (2 ** rel - 1)
                / np.log2(i + 1)
            )
        
        ideal_relevance = np.sort(
            relevance
        )[::-1]
        
        idcg = 0.0
        
        for i, rel in enumerate(
            ideal_relevance,
            start=1
        ):
            idcg += (
                (2 ** rel - 1)
                / np.log2(i + 1)
            )
        
        if idcg == 0:
            score = 0.0
        else:
            score = dcg / idcg
        
        scores.append(score)
    
    if len(scores) == 0:
        return np.nan
    
    return np.mean(scores)

In [32]:
ndcg_comparison = []

for k in [1, 3, 5, 10]:
    
    demand_ndcg = calculate_ndcg_from_ground_truth(
        final_recommendations,
        ground_truth,
        "demand_aware_rank",
        k
    )
    
    b5_ndcg = calculate_ndcg_from_ground_truth(
        b5_eval_clean,
        ground_truth,
        "rank",
        k
    )
    
    ndcg_comparison.append({
        "k": k,
        "B5_NDCG": b5_ndcg,
        "Demand_Aware_NDCG": demand_ndcg,
        "NDCG_change":
            demand_ndcg - b5_ndcg
    })

ndcg_comparison = pd.DataFrame(
    ndcg_comparison
)

display(ndcg_comparison)

    k   B5_NDCG  Demand_Aware_NDCG  NDCG_change
0   1  0.080000           0.080000     0.000000
1   3  0.165474           0.161606    -0.003869
2   5  0.209814           0.210895     0.001082
3  10  0.260146           0.256152    -0.003994

In [33]:
final_evaluation_path = (
    RESULTS_DIR /
    "final_model_evaluation.csv"
)

comparison_metrics.to_csv(
    final_evaluation_path,
    index=False
)

print(
    "Saved:",
    final_evaluation_path
)

Saved: ..\results\final_model_evaluation.csv

In [34]:
ndcg_path = (
    RESULTS_DIR /
    "ndcg_evaluation.csv"
)

ndcg_comparison.to_csv(
    ndcg_path,
    index=False
)

print(
    "Saved:",
    ndcg_path
)

Saved: ..\results\ndcg_evaluation.csv

In [35]:
print("========== NOTEBOOK 07 FINAL VALIDATION ==========")

assert len(ground_truth) == 500
assert ground_truth["user_id"].nunique() == 50

assert len(demand_aware_metrics) == 4
assert len(b5_metrics) == 4

assert len(ndcg_comparison) == 4

assert final_evaluation_path.exists()
assert ndcg_path.exists()

print("Ground-truth cases:", len(ground_truth))
print("Users:", ground_truth["user_id"].nunique())

print("\nPrecision@K: ✓")
print("Recall@K: ✓")
print("NDCG@K: ✓")
print("B5 comparison: ✓")
print("Demand-aware comparison: ✓")

print("\nEvaluation files saved: ✓")

print("\n✓ NOTEBOOK 07 COMPLETED SUCCESSFULLY")

========== NOTEBOOK 07 FINAL VALIDATION ==========
Ground-truth cases: 500
Users: 50

Precision@K: ✓
Recall@K: ✓
NDCG@K: ✓
B5 comparison: ✓
Demand-aware comparison: ✓

Evaluation files saved: ✓

✓ NOTEBOOK 07 COMPLETED SUCCESSFULLY