In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
PROJECT_DIR = Path("../")
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"

print("Project:", PROJECT_DIR.resolve())
print("Data:", DATA_DIR.resolve())
print("Results:", RESULTS_DIR.resolve())

Project: C:\Users\ASUS\Documents\Smart-Tourism-Recommendation
Data: C:\Users\ASUS\Documents\Smart-Tourism-Recommendation\data
Results: C:\Users\ASUS\Documents\Smart-Tourism-Recommendation\results

In [3]:
required_files = [
    "demand_aware_recommendations.csv",
    "final_model_evaluation.csv",
    "ndcg_evaluation.csv",
    "model_comparison_metrics.csv",
    "model_metric_changes.csv",
    "explainable_recommendations.csv"
]

print("========== REQUIRED FILE CHECK ==========")

for filename in required_files:
    path = RESULTS_DIR / filename
    
    print(
        f"{filename}:",
        "✓ EXISTS" if path.exists() else "✗ MISSING"
    )

========== REQUIRED FILE CHECK ==========
demand_aware_recommendations.csv: ✓ EXISTS
final_model_evaluation.csv: ✓ EXISTS
ndcg_evaluation.csv: ✓ EXISTS
model_comparison_metrics.csv: ✓ EXISTS
model_metric_changes.csv: ✗ MISSING
explainable_recommendations.csv: ✓ EXISTS

In [4]:
comparison_path = RESULTS_DIR / "model_comparison_metrics.csv"

comparison = pd.read_csv(comparison_path)

print("Comparison columns:")
print(comparison.columns.tolist())

display(comparison)

Comparison columns:
['Model', 'Precision@5', 'Recall@5', 'NDCG@5']

                   Model  Precision@5  Recall@5    NDCG@5
0  B1 - General Baseline     0.011111  0.027778  0.559349
1     B2 - Content-Based     0.072222  0.189815  0.627412
2     B3 - Context-Aware     0.083333  0.222222  0.612713
3            B4 - Hybrid     0.088889  0.254630  0.553025

In [5]:
model_metric_changes = comparison.copy()

print("Creating model metric changes...")

# Add change columns when the required columns exist
if (
    "precision_demand_aware" in model_metric_changes.columns
    and "precision_b5" in model_metric_changes.columns
):
    model_metric_changes["precision_change"] = (
        model_metric_changes["precision_demand_aware"]
        - model_metric_changes["precision_b5"]
    )

if (
    "recall_demand_aware" in model_metric_changes.columns
    and "recall_b5" in model_metric_changes.columns
):
    model_metric_changes["recall_change"] = (
        model_metric_changes["recall_demand_aware"]
        - model_metric_changes["recall_b5"]
    )

if (
    "average_hits_demand_aware" in model_metric_changes.columns
    and "average_hits_b5" in model_metric_changes.columns
):
    model_metric_changes["hit_change"] = (
        model_metric_changes["average_hits_demand_aware"]
        - model_metric_changes["average_hits_b5"]
    )

changes_path = (
    RESULTS_DIR / "model_metric_changes.csv"
)

model_metric_changes.to_csv(
    changes_path,
    index=False
)

print("Saved:", changes_path)
print("Exists:", changes_path.exists())

display(model_metric_changes)

Creating model metric changes...
Saved: ..\results\model_metric_changes.csv
Exists: True

                   Model  Precision@5  Recall@5    NDCG@5
0  B1 - General Baseline     0.011111  0.027778  0.559349
1     B2 - Content-Based     0.072222  0.189815  0.627412
2     B3 - Context-Aware     0.083333  0.222222  0.612713
3            B4 - Hybrid     0.088889  0.254630  0.553025

In [6]:
required_files = [
    "demand_aware_recommendations.csv",
    "final_model_evaluation.csv",
    "ndcg_evaluation.csv",
    "model_comparison_metrics.csv",
    "model_metric_changes.csv",
    "explainable_recommendations.csv"
]

print("========== REQUIRED FILE CHECK ==========")

all_exist = True

for filename in required_files:
    path = RESULTS_DIR / filename
    exists = path.exists()

    print(
        f"{filename}:",
        "✓ EXISTS" if exists else "✗ MISSING"
    )

    if not exists:
        all_exist = False

assert all_exist

print("\n✓ ALL REQUIRED OUTPUT FILES EXIST")

========== REQUIRED FILE CHECK ==========
demand_aware_recommendations.csv: ✓ EXISTS
final_model_evaluation.csv: ✓ EXISTS
ndcg_evaluation.csv: ✓ EXISTS
model_comparison_metrics.csv: ✓ EXISTS
model_metric_changes.csv: ✓ EXISTS
explainable_recommendations.csv: ✓ EXISTS

✓ ALL REQUIRED OUTPUT FILES EXIST

In [7]:
final_recommendations = pd.read_csv(
    RESULTS_DIR / "demand_aware_recommendations.csv"
)

print("Rows:", len(final_recommendations))
print("Users:", final_recommendations["user_id"].nunique())
print(
    "Destinations:",
    final_recommendations["destination_id"].nunique()
)

Rows: 500
Users: 50
Destinations: 77

In [8]:
recommendation_counts = (
    final_recommendations
    .groupby("user_id")
    .size()
)

print(recommendation_counts.value_counts())

assert recommendation_counts.min() == 10
assert recommendation_counts.max() == 10

print("10 recommendations per user: ✓")

10    50
Name: count, dtype: int64
10 recommendations per user: ✓

In [9]:
print(
    "Minimum rank:",
    final_recommendations["demand_aware_rank"].min()
)

print(
    "Maximum rank:",
    final_recommendations["demand_aware_rank"].max()
)

assert final_recommendations[
    "demand_aware_rank"
].min() == 1

assert final_recommendations[
    "demand_aware_rank"
].max() == 10

print("Ranks 1–10: ✓")

Minimum rank: 1
Maximum rank: 10
Ranks 1–10: ✓

In [10]:
explainable = pd.read_csv(
    RESULTS_DIR / "explainable_recommendations.csv"
)

print("Rows:", len(explainable))
print("Users:", explainable["user_id"].nunique())

assert len(explainable) == 500
assert explainable["user_id"].nunique() == 50

print("Explainable recommendations: ✓")

Rows: 500
Users: 50
Explainable recommendations: ✓

In [11]:
print(
    "Missing basic explanations:",
    explainable["explanation"].isna().sum()
)

print(
    "Missing detailed explanations:",
    explainable["detailed_explanation"].isna().sum()
)

assert explainable["explanation"].notna().all()
assert explainable["detailed_explanation"].notna().all()

print("All explanations present: ✓")

Missing basic explanations: 0
Missing detailed explanations: 0
All explanations present: ✓

In [12]:
sample_user = explainable["user_id"].iloc[0]

display(
    explainable[
        explainable["user_id"] == sample_user
    ][
        [
            "demand_aware_rank",
            "name",
            "category",
            "estimated_cost_lkr",
            "predicted_crowd_level",
            "demand_aware_score",
            "explanation"
        ]
    ].sort_values(
        "demand_aware_rank"
    )
)

,demand_aware_rank,name,category,estimated_cost_lkr,predicted_crowd_level,demand_aware_score,explanation
0,1,Colombo National Museum,heritage;culture,3000,Low,0.638371,Recommended because of good match with your tr...
1,2,Viharamahadevi Park,nature;city,2000,Low,0.614931,Recommended because of good match with your tr...
2,3,Ella Rock,nature;adventure,5000,Low,0.588797,Recommended because of some alignment with you...
3,4,Mount Lavinia Beach,beach,5000,Low,0.558387,Recommended because of some alignment with you...
4,5,Dutch Hospital Colombo,heritage;city,5000,Medium,0.547760,Recommended because of good match with your tr...
5,6,Nuwara Eliya City,city;nature,5000,Medium,0.524035,Recommended because of some alignment with you...
6,7,Bopath Ella,nature,3000,Medium,0.516999,Recommended because of good match with your tr...
7,8,Ohiya,nature;adventure,5000,Medium,0.489361,Recommended because of good match with your tr...
8,9,Brief Garden,nature,4000,Medium,0.459681,Recommended because of some alignment with you...
9,10,Independence Square,heritage;city,2000,Medium,0.439264,Recommended because of good match with your tr...

In [13]:
evaluation = pd.read_csv(
    RESULTS_DIR / "final_model_evaluation.csv"
)

ndcg = pd.read_csv(
    RESULTS_DIR / "ndcg_evaluation.csv"
)

comparison = pd.read_csv(
    RESULTS_DIR / "model_comparison_metrics.csv"
)

print("Final evaluation rows:", len(evaluation))
print("NDCG rows:", len(ndcg))
print("Comparison rows:", len(comparison))

print("\nFinal evaluation:")
display(evaluation)

print("\nNDCG evaluation:")
display(ndcg)

print("\nModel comparison:")
display(comparison)

Final evaluation rows: 4
NDCG rows: 4
Comparison rows: 4

Final evaluation:

,k,precision_demand_aware,recall_demand_aware,average_hits_demand_aware,precision_b5,recall_b5,average_hits_b5,precision_change,recall_change,hit_change
0,1,0.060,0.055556,0.06,0.080,0.069444,0.08,-0.020,-0.013889,-0.02
1,3,0.060,0.138889,0.18,0.060,0.162037,0.18,0.000,-0.023148,0.00
2,5,0.056,0.217593,0.28,0.044,0.189815,0.22,0.012,0.027778,0.06
3,10,0.042,0.337963,0.42,0.042,0.337963,0.42,0.000,0.000000,0.00

NDCG evaluation:

    k   B5_NDCG  Demand_Aware_NDCG  NDCG_change
0   1  0.080000           0.080000     0.000000
1   3  0.165474           0.161606    -0.003869
2   5  0.209814           0.210895     0.001082
3  10  0.260146           0.256152    -0.003994

Model comparison:

                   Model  Precision@5  Recall@5    NDCG@5
0  B1 - General Baseline     0.011111  0.027778  0.559349
1     B2 - Content-Based     0.072222  0.189815  0.627412
2     B3 - Context-Aware     0.083333  0.222222  0.612713
3            B4 - Hybrid     0.088889  0.254630  0.553025

In [15]:
print("Comparison shape:", comparison.shape)
print("Comparison rows:", len(comparison))

print("\nColumns:")
print(comparison.columns.tolist())

print("\nContents:")
display(comparison)

Comparison shape: (4, 4)
Comparison rows: 4

Columns:
['Model', 'Precision@5', 'Recall@5', 'NDCG@5']

Contents:

                   Model  Precision@5  Recall@5    NDCG@5
0  B1 - General Baseline     0.011111  0.027778  0.559349
1     B2 - Content-Based     0.072222  0.189815  0.627412
2     B3 - Context-Aware     0.083333  0.222222  0.612713
3            B4 - Hybrid     0.088889  0.254630  0.553025

In [16]:
metric_changes = pd.read_csv(
    RESULTS_DIR / "model_metric_changes.csv"
)

print("Metric changes shape:", metric_changes.shape)
print("Metric changes rows:", len(metric_changes))

print("\nColumns:")
print(metric_changes.columns.tolist())

display(metric_changes)

Metric changes shape: (4, 4)
Metric changes rows: 4

Columns:
['Model', 'Precision@5', 'Recall@5', 'NDCG@5']

                   Model  Precision@5  Recall@5    NDCG@5
0  B1 - General Baseline     0.011111  0.027778  0.559349
1     B2 - Content-Based     0.072222  0.189815  0.627412
2     B3 - Context-Aware     0.083333  0.222222  0.612713
3            B4 - Hybrid     0.088889  0.254630  0.553025

In [17]:
print("========== FINAL PROJECT VALIDATION ==========")

# Final recommendation checks
assert len(final_recommendations) == 500
assert final_recommendations["user_id"].nunique() == 50

assert (
    final_recommendations
    .groupby("user_id")
    .size()
    .eq(10)
    .all()
)

assert (
    final_recommendations["demand_aware_rank"]
    .between(1, 10)
    .all()
)

# Explainability checks
assert len(explainable) == 500
assert explainable["user_id"].nunique() == 50

assert explainable["explanation"].notna().all()
assert explainable["detailed_explanation"].notna().all()

# Evaluation checks
assert len(evaluation) > 0
assert len(ndcg) == 4

# B1-B4 comparison
assert len(comparison) == 4

expected_models = [
    "B1 - General Baseline",
    "B2 - Content-Based",
    "B3 - Context-Aware",
    "B4 - Hybrid"
]

for model_name in expected_models:
    assert model_name in comparison["Model"].values

# Required metric columns
required_metrics = [
    "Precision@5",
    "Recall@5",
    "NDCG@5"
]

for col in required_metrics:
    assert col in comparison.columns

print("50 users: ✓")
print("500 final recommendations: ✓")
print("10 recommendations per user: ✓")
print("Ranks 1–10: ✓")
print("Explanations: ✓")
print("Detailed explanations: ✓")
print("Final evaluation: ✓")
print("NDCG evaluation: ✓")
print("B1–B4 comparison: ✓")

print()
print("✓ COMPLETE ML PIPELINE VALIDATED")

========== FINAL PROJECT VALIDATION ==========
50 users: ✓
500 final recommendations: ✓
10 recommendations per user: ✓
Ranks 1–10: ✓
Explanations: ✓
Detailed explanations: ✓
Final evaluation: ✓
NDCG evaluation: ✓
B1–B4 comparison: ✓

✓ COMPLETE ML PIPELINE VALIDATED

In [1]:
import os

for root, dirs, files in os.walk("../data"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

../data\features\destinations_with_crowd_predictions.csv
../data\features\destination_features.csv
../data\features\destination_text.csv
../data\features\evaluation_features.csv
../data\features\user_features.csv
../data\features\user_text.csv
../data\processed\destinations_clean.csv
../data\processed\evaluation_cases_clean.csv
../data\processed\preprocessing_report.csv
../data\processed\user_profiles_clean.csv
../data\raw\destinations.csv
../data\raw\evaluation_cases_500.csv
../data\raw\user_profiles.csv

In [2]:
import os
import pandas as pd

print("========== SEARCHING FOR RECOMMENDATION FILES ==========")

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith((".csv", ".parquet", ".json")):
            path = os.path.join(root, file)

            try:
                df = pd.read_csv(path)

                # Look for files with approximately 500 rows
                if len(df) == 500:
                    print(f"\nFOUND 500-ROW FILE:")
                    print(path)
                    print("Shape:", df.shape)
                    print("Columns:", df.columns.tolist())

            except Exception:
                pass

========== SEARCHING FOR RECOMMENDATION FILES ==========

FOUND 500-ROW FILE:
..\data\features\evaluation_features.csv
Shape: (500, 17)
Columns: ['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5']

FOUND 500-ROW FILE:
..\data\processed\evaluation_cases_clean.csv
Shape: (500, 27)
Columns: ['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'travel_style', 'starting_location', 'preferred_interests', 'preferred_crowd', 'preferred_weather', 'destination_name', 'destination_category', 'estimated_cost_lkr', 'duration_hours', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5', 'data_status']

FOUND 500-ROW FILE:
..\data\raw\evaluation_cases_500.csv
Shape: (500, 27)
Columns: ['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'travel_style', 'starting_location', 'preferred_interests', 'preferred_crowd', 'preferred_weather', 'destination_name', 'destination_category', 'estimated_cost_lkr', 'duration_hours', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5', 'data_status']

FOUND 500-ROW FILE:
..\results\b1_general_baseline_all_users_top10.csv
Shape: (500, 7)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'rank', 'baseline_score']

FOUND 500-ROW FILE:
..\results\b2_content_based_all_users_top10.csv
Shape: (500, 7)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'content_similarity', 'rank']

FOUND 500-ROW FILE:
..\results\b3_context_aware_all_users_top10.csv
Shape: (500, 14)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'preference_score', 'budget_fit', 'crowd_fit', 'weather_fit', 'sustainability_fit', 'seasonality_fit', 'sentiment_fit', 'context_score', 'rank']

FOUND 500-ROW FILE:
..\results\b4_hybrid_explainable_recommendations.csv
Shape: (500, 21)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'sentiment_model', 'preference_model', 'budget_model', 'crowd_model', 'weather_model', 'sustainability_model', 'seasonality_model', 'hybrid_score', 'explanation']

FOUND 500-ROW FILE:
..\results\b4_hybrid_recommendations.csv
Shape: (500, 23)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'content_similarity', 'content_similarity_normalized', 'preference_score', 'budget_score', 'crowd_fit_score', 'weather_fit_score', 'context_score', 'hybrid_score', 'rank', 'explanation']

FOUND 500-ROW FILE:
..\results\b5_sbert_semantic_all_users_top10.csv
Shape: (500, 12)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_suitability', 'semantic_similarity', 'rank']

FOUND 500-ROW FILE:
..\results\b5_sbert_semantic_recommendations.csv
Shape: (500, 20)
Columns: ['user_id', 'destination_id', 'content_similarity', 'content_similarity_normalized', 'sbert_similarity', 'sbert_similarity_normalized', 'interest_match', 'budget_fit', 'sustainability_fit', 'context_score', 'sbert_hybrid_score', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'seasonality_score', 'rank']

FOUND 500-ROW FILE:
..\results\d1_sbert_semantic_recommendations.csv
Shape: (500, 6)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'sbert_similarity']

FOUND 500-ROW FILE:
..\results\demand_aware_ranking_comparison.csv
Shape: (500, 11)
Columns: ['user_id', 'destination_id', 'name', 'rank', 'sbert_hybrid_score', 'predicted_crowd_score', 'predicted_crowd_level', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'rank_change']

FOUND 500-ROW FILE:
..\results\demand_aware_recommendations.csv
Shape: (500, 17)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'predicted_crowd_score', 'predicted_crowd_level', 'seasonality_score', 'sbert_hybrid_score', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'demand_explanation']

FOUND 500-ROW FILE:
..\results\explainable_recommendations.csv
Shape: (500, 14)
Columns: ['user_id', 'destination_id', 'name', 'category', 'estimated_cost_lkr', 'sustainability_score', 'predicted_crowd_score', 'predicted_crowd_level', 'sbert_hybrid_score', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'explanation', 'detailed_explanation']

FOUND 500-ROW FILE:
..\results\final_demand_aware_recommendations.csv
Shape: (500, 27)
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'sentiment_nature', 'sentiment_service', 'sentiment_value', 'predicted_crowd_score', 'predicted_crowd_level', 'preference_score', 'budget_fit', 'predicted_crowd_fit', 'weather_fit', 'sustainability_fit', 'sentiment_fit', 'demand_suitability', 'demand_aware_score', 'explanation', 'seasonality_normalized', 'predicted_crowd_normalized']

In [3]:
print("========== 500-ROW DATAFRAMES ==========")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        if len(obj) == 500:
            print("\nVARIABLE:", name)
            print("Shape:", obj.shape)
            print("Columns:", obj.columns.tolist())

========== 500-ROW DATAFRAMES ==========

In [4]:
import os
import pandas as pd

print("========== SEARCHING ALL CSV FILES ==========")

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith(".csv"):
            path = os.path.join(root, file)

            try:
                df = pd.read_csv(path, nrows=5)
                cols = set(df.columns)

                has_user = "user_id" in cols
                has_destination = "destination_id" in cols
                has_rank = any(
                    c in cols
                    for c in [
                        "rank",
                        "recommendation_rank",
                        "demand_aware_rank"
                    ]
                )
                has_explanation = any(
                    c in cols
                    for c in [
                        "explanation",
                        "detailed_explanation"
                    ]
                )

                if has_user and has_destination:
                    print("\nFILE:", path)
                    print("Columns:", df.columns.tolist())
                    print(
                        "User:",
                        has_user,
                        "| Destination:",
                        has_destination,
                        "| Rank:",
                        has_rank,
                        "| Explanation:",
                        has_explanation
                    )

            except Exception:
                pass

========== SEARCHING ALL CSV FILES ==========

FILE: ..\data\features\evaluation_features.csv
Columns: ['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5']
User: True | Destination: True | Rank: False | Explanation: False

FILE: ..\data\processed\evaluation_cases_clean.csv
Columns: ['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'travel_style', 'starting_location', 'preferred_interests', 'preferred_crowd', 'preferred_weather', 'destination_name', 'destination_category', 'estimated_cost_lkr', 'duration_hours', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5', 'data_status']
User: True | Destination: True | Rank: False | Explanation: False

FILE: ..\data\raw\evaluation_cases_500.csv
Columns: ['case_id', 'user_id', 'destination_id', 'scenario_id', 'user_budget_lkr_per_day', 'trip_duration_days', 'travel_style', 'starting_location', 'preferred_interests', 'preferred_crowd', 'preferred_weather', 'destination_name', 'destination_category', 'estimated_cost_lkr', 'duration_hours', 'distance_km', 'preference_score', 'budget_score', 'sustainability_score', 'crowd_fit_score', 'context_score', 'distance_score', 'sentiment_score', 'popularity_score', 'overall_hybrid_score', 'relevance_rating_1_to_5', 'data_status']
User: True | Destination: True | Rank: False | Explanation: False

FILE: ..\results\b1_general_baseline_all_users_top10.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'rank', 'baseline_score']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\b2_content_based_all_users_top10.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'content_similarity', 'rank']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\b3_context_aware_all_users_top10.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'preference_score', 'budget_fit', 'crowd_fit', 'weather_fit', 'sustainability_fit', 'seasonality_fit', 'sentiment_fit', 'context_score', 'rank']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\b4_hybrid_all_candidates.csv
Columns: ['user_id', 'destination_id', 'content_similarity', 'content_similarity_normalized', 'context_score', 'hybrid_score']
User: True | Destination: True | Rank: False | Explanation: False

FILE: ..\results\b4_hybrid_all_users_top10.csv
Columns: ['user_id', 'destination_id', 'content_similarity', 'content_similarity_normalized', 'context_score', 'hybrid_score', 'rank', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'explanation']
User: True | Destination: True | Rank: True | Explanation: True

FILE: ..\results\b4_hybrid_explainable_recommendations.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'sentiment_model', 'preference_model', 'budget_model', 'crowd_model', 'weather_model', 'sustainability_model', 'seasonality_model', 'hybrid_score', 'explanation']
User: True | Destination: True | Rank: False | Explanation: True

FILE: ..\results\b4_hybrid_recommendations.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'content_similarity', 'content_similarity_normalized', 'preference_score', 'budget_score', 'crowd_fit_score', 'weather_fit_score', 'context_score', 'hybrid_score', 'rank', 'explanation']
User: True | Destination: True | Rank: True | Explanation: True

FILE: ..\results\b5_sbert_semantic_all_users_top10.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'crowd_score', 'seasonality_score', 'weather_suitability', 'semantic_similarity', 'rank']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\b5_sbert_semantic_recommendations.csv
Columns: ['user_id', 'destination_id', 'content_similarity', 'content_similarity_normalized', 'sbert_similarity', 'sbert_similarity_normalized', 'interest_match', 'budget_fit', 'sustainability_fit', 'context_score', 'sbert_hybrid_score', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'seasonality_score', 'rank']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\d1_sbert_semantic_recommendations.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'sbert_similarity']
User: True | Destination: True | Rank: False | Explanation: False

FILE: ..\results\demand_aware_ranking_comparison.csv
Columns: ['user_id', 'destination_id', 'name', 'rank', 'sbert_hybrid_score', 'predicted_crowd_score', 'predicted_crowd_level', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'rank_change']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\demand_aware_recommendations.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'duration_hours', 'sustainability_score', 'crowd_score', 'predicted_crowd_score', 'predicted_crowd_level', 'seasonality_score', 'sbert_hybrid_score', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'demand_explanation']
User: True | Destination: True | Rank: True | Explanation: False

FILE: ..\results\explainable_recommendations.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'estimated_cost_lkr', 'sustainability_score', 'predicted_crowd_score', 'predicted_crowd_level', 'sbert_hybrid_score', 'crowd_suitability', 'demand_aware_score', 'demand_aware_rank', 'explanation', 'detailed_explanation']
User: True | Destination: True | Rank: True | Explanation: True

FILE: ..\results\final_demand_aware_recommendations.csv
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'sentiment_nature', 'sentiment_service', 'sentiment_value', 'predicted_crowd_score', 'predicted_crowd_level', 'preference_score', 'budget_fit', 'predicted_crowd_fit', 'weather_fit', 'sustainability_fit', 'sentiment_fit', 'demand_suitability', 'demand_aware_score', 'explanation', 'seasonality_normalized', 'predicted_crowd_normalized']
User: True | Destination: True | Rank: False | Explanation: True

In [5]:
import pandas as pd

final_path = "../results/final_demand_aware_recommendations.csv"

final_recommendations = pd.read_csv(final_path)

print("========== FINAL DEMAND-AWARE RECOMMENDATIONS ==========")
print("Shape:", final_recommendations.shape)
print("Users:", final_recommendations["user_id"].nunique())
print("Columns:", final_recommendations.columns.tolist())

print("\nRecommendations per user:")
print(final_recommendations.groupby("user_id").size().value_counts())

print("\nRows per user:")
print(final_recommendations.groupby("user_id").size().head(10))

print("\nSample:")
display(final_recommendations.head(10))

========== FINAL DEMAND-AWARE RECOMMENDATIONS ==========
Shape: (500, 27)
Users: 50
Columns: ['user_id', 'destination_id', 'name', 'category', 'district', 'estimated_cost_lkr', 'sustainability_score', 'seasonality_score', 'weather_temp_c', 'weather_rain_risk', 'weather_suitability', 'sentiment_nature', 'sentiment_service', 'sentiment_value', 'predicted_crowd_score', 'predicted_crowd_level', 'preference_score', 'budget_fit', 'predicted_crowd_fit', 'weather_fit', 'sustainability_fit', 'sentiment_fit', 'demand_suitability', 'demand_aware_score', 'explanation', 'seasonality_normalized', 'predicted_crowd_normalized']

Recommendations per user:
10    50
Name: count, dtype: int64

Rows per user:
user_id
U001    10
U002    10
U003    10
U004    10
U005    10
U006    10
U007    10
U008    10
U009    10
U010    10
dtype: int64

Sample:

,user_id,destination_id,name,category,district,estimated_cost_lkr,sustainability_score,seasonality_score,weather_temp_c,weather_rain_risk,...,budget_fit,predicted_crowd_fit,weather_fit,sustainability_fit,sentiment_fit,demand_suitability,demand_aware_score,explanation,seasonality_normalized,predicted_crowd_normalized
0,U001,D083,Hummanaya Blow Hole,nature;coastal,matara,3000,58,67,25.9,0.173,...,1.000000,0.0,0.6948,0.7,0.800667,0.668605,0.505335,fits your budget; good sustainability alignment,0.952381,0.331395
1,U001,D028,Pidurutalagala View Area,nature,nuwara eliya,3000,60,68,26.8,0.399,...,1.000000,0.0,0.5684,0.7,0.803333,0.652435,0.503000,fits your budget; good sustainability alignment,1.000000,0.347565
2,U001,D017,Udawattakele Forest Reserve,nature,kandy,3000,72,67,26.1,0.296,...,1.000000,0.0,0.6376,0.7,0.861333,0.719844,0.485042,fits your budget; good sustainability alignment,0.952381,0.280156
3,U001,D031,Nine Arches Bridge,heritage;nature,badulla,3000,66,68,30.8,0.032,...,1.000000,0.0,0.5552,0.7,0.693000,0.708045,0.460385,fits your budget; good sustainability alignment,1.000000,0.291955
4,U001,D062,Adam's Peak,religious;nature,ratnapura,5000,62,65,27.5,0.372,...,1.000000,0.0,0.5512,0.7,0.801000,0.710220,0.453532,fits your budget; good sustainability alignment,0.857143,0.289780
5,U001,D061,Belilena Cave,heritage;nature,kegalle,3000,61,68,29.9,0.335,...,1.000000,0.0,0.4700,0.7,0.662333,0.700722,0.439759,fits your budget; good sustainability alignment,1.000000,0.299278
6,U001,D068,Ratnapura Gem Museum Area,culture;heritage,ratnapura,4000,56,62,29.8,0.086,...,1.000000,0.0,0.5736,0.7,0.708333,0.736572,0.420736,fits your budget; good sustainability alignment,0.714286,0.263428
7,U001,D009,Wilpattu National Park,wildlife;nature,puttalam,16000,63,68,27.6,0.173,...,0.312500,0.0,0.6268,0.7,0.738667,0.693101,0.398651,good sustainability alignment,1.000000,0.306899
8,U001,D063,Sinharaja Forest Reserve,nature;wildlife,ratnapura,8000,69,67,29.4,0.261,...,0.625000,0.0,0.5196,0.7,0.695333,0.724895,0.397267,good sustainability alignment,0.952381,0.275105
9,U001,D064,Udawalawe National Park,wildlife;nature,ratnapura,15000,64,66,29.9,0.244,...,0.333333,0.0,0.5064,0.7,0.756333,0.729667,0.387686,good sustainability alignment,0.904762,0.270333